package report

import (
	"fmt"
	"html/template"
	"strings"
)

var funcs = template.FuncMap{
	"shortHash": func(s string) string {
		if len(s) > 12 {
			return s[:12]
		}
		return s
	},
	"humanBytes": humanBytes,
	"depth": func(p string) string {
		return strings.Repeat("../", strings.Count(p, "/"))
	},
	"badge": func(kind string) template.HTML {
		k := template.HTMLEscapeString(kind)
		return template.HTML(`<span class="badge ` + k + `">` + k + `</span>`)
	},
	"sevBadge": func(sev string) template.HTML {
		s := template.HTMLEscapeString(sev)
		return template.HTML(`<span class="sev sev-` + s + `">` + s + `</span>`)
	},
	"evtBadge": func(t string) template.HTML {
		s := template.HTMLEscapeString(t)
		return template.HTML(`<span class="evt">` + s + `</span>`)
	},
	"yesNo": func(b bool) string {
		if b {
			return "yes"
		}
		return "no"
	},
	"numberedLines": numberedLines,
}

// numberedLines renders text with per-line span anchors (id="line-N") so the
// PXC timeline and other deep-link sources can scroll to a specific line.
func numberedLines(s string) template.HTML {
	if s == "" {
		return ""
	}
	// Strip a single trailing newline so we don't produce a blank final span.
	if strings.HasSuffix(s, "\n") {
		s = s[:len(s)-1]
	}
	lines := strings.Split(s, "\n")
	var b strings.Builder
	b.Grow(len(s) + 32*len(lines))
	for i, line := range lines {
		fmt.Fprintf(&b, `<span class="ln" id="line-%d">`, i+1)
		b.WriteString(template.HTMLEscapeString(line))
		b.WriteString("</span>\n")
	}
	return template.HTML(b.String())
}

func humanBytes(n int64) string {
	const unit = 1024
	if n < unit {
		return fmt.Sprintf("%d B", n)
	}
	div, exp := int64(unit), 0
	for x := n / unit; x >= unit; x /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f %cB", float64(n)/float64(div), "KMGTPE"[exp])
}

const baseHeader = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{{.Title}} — db-k8s</title>
<link rel="stylesheet" href="{{.AssetBase}}assets/style.css">
</head>
<body>
<header class="site">
  <h1>db-k8s</h1>
  <nav>
    <a href="{{.AssetBase}}index.html"{{if eq .Nav "index"}} class="active"{{end}}>Overview</a>
    <a href="{{.AssetBase}}concerns.html"{{if eq .Nav "concerns"}} class="active"{{end}}>Concerns</a>
    <a href="{{.AssetBase}}files.html"{{if eq .Nav "files"}} class="active"{{end}}>Files</a>
    <a href="{{.AssetBase}}objects.html"{{if eq .Nav "objects"}} class="active"{{end}}>Kubernetes Objects</a>
    <a href="{{.AssetBase}}pxc-timeline.html"{{if eq .Nav "timeline"}} class="active"{{end}}>PXC Timeline</a>
    <a href="{{.AssetBase}}backups.html"{{if eq .Nav "backups"}} class="active"{{end}}>Backups</a>
  </nav>
</header>
<main>
`

const baseFooter = `
</main>
<footer class="site">
  Generated by db-k8s · {{.GeneratedAt}}
</footer>
<script src="{{.AssetBase}}assets/script.js"></script>
</body>
</html>`

const indexBody = `
<h2>Overview</h2>
<div class="cards">
  <div class="card"><div class="label">Dumps</div><div class="value">{{.TotalDumps}}</div></div>
  <div class="card"><div class="label">Files</div><div class="value">{{.TotalFiles}}</div></div>
  <div class="card"><div class="label">Total bytes</div><div class="value">{{humanBytes .TotalBytes}}</div></div>
  <div class="card sev-card critical"><div class="label">Critical</div><div class="value">{{.Critical}}</div></div>
  <div class="card sev-card warning"><div class="label">Warning</div><div class="value">{{.Warning}}</div></div>
  <div class="card sev-card info"><div class="label">Info</div><div class="value">{{.Info}}</div></div>
</div>

<div class="cards">
  <div class="card"><div class="label">YAML</div><div class="value">{{index .KindCounts "yaml"}}</div></div>
  <div class="card"><div class="label">JSON</div><div class="value">{{index .KindCounts "json"}}</div></div>
  <div class="card"><div class="label">Text</div><div class="value">{{index .KindCounts "text"}}</div></div>
  <div class="card"><div class="label">Binary</div><div class="value">{{index .KindCounts "binary"}}</div></div>
  <div class="card"><div class="label">Unknown</div><div class="value">{{index .KindCounts "unknown"}}</div></div>
</div>

{{if gt .BackupTotal 0}}
<h3>Backups</h3>
<div class="cards">
  <div class="card"><div class="label">Operations</div><div class="value">{{.BackupTotal}}</div></div>
  <div class="card sev-card info"><div class="label">Succeeded</div><div class="value">{{.BackupSucceeded}}</div></div>
  <div class="card sev-card critical"><div class="label">Failed</div><div class="value">{{.BackupFailed}}</div></div>
  <div class="card sev-card warning"><div class="label">Running</div><div class="value">{{.BackupRunning}}</div></div>
  <div class="card"><div class="label">Pending</div><div class="value">{{.BackupPending}}</div></div>
  <div class="card"><div class="label">Unknown</div><div class="value">{{.BackupUnknown}}</div></div>
</div>
<p><a href="backups.html">Open the backup summary →</a></p>
{{end}}

{{if gt .PXCEvents 0}}
<h3>PXC Timeline</h3>
<div class="cards">
  <div class="card"><div class="label">Dumps with PXC logs</div><div class="value">{{.PXCDumps}}</div></div>
  <div class="card"><div class="label">PXC nodes detected</div><div class="value">{{.PXCNodes}}</div></div>
  <div class="card"><div class="label">Parsed events</div><div class="value">{{.PXCEvents}}</div></div>
  <div class="card sev-card warning"><div class="label">Log warnings</div><div class="value">{{.PXCWarnings}}</div></div>
  <div class="card sev-card critical"><div class="label">Log errors</div><div class="value">{{.PXCErrors}}</div></div>
</div>
<p><a href="pxc-timeline.html">Open the side-by-side PXC timeline →</a></p>
{{end}}

{{if .TopCritical}}
<h3>Top critical concerns</h3>
<table>
<thead><tr><th>Severity</th><th>Rule</th><th>Object</th><th>Title</th></tr></thead>
<tbody>
{{range .TopCritical}}
<tr>
  <td>{{sevBadge .Severity}}</td>
  <td class="mono">{{.Rule}}</td>
  <td><a href="{{.FileHref}}">{{.Kind}} {{.Namespace}}/{{.Name}}</a></td>
  <td>{{.Title}}</td>
</tr>
{{end}}
</tbody>
</table>
<p><a href="concerns.html">See all concerns →</a></p>
{{end}}

<h3>Database</h3>
<p class="mono">{{.DBPath}}</p>

<h3>Dumps</h3>
<table>
<thead><tr><th>ID</th><th>Root</th><th>Source</th><th>Type</th><th>Files</th><th>Size</th><th>Imported</th></tr></thead>
<tbody>
{{range .Dumps}}
<tr>
  <td><a href="dumps/dump-{{.ID}}.html">{{.ID}}</a></td>
  <td>{{.RootName}}</td>
  <td class="mono">{{.SourcePath}}</td>
  <td>{{.SourceType}}</td>
  <td>{{.FileCount}}</td>
  <td>{{humanBytes .Bytes}}</td>
  <td>{{.ImportedAt}}</td>
</tr>
{{end}}
</tbody>
</table>
`

const filesBody = `
<h2>Files</h2>
<form id="files-form" class="toolbar" onsubmit="return false;">
  <input type="search" placeholder="Filter by path, name, hash, namespace…" autocomplete="off">
  <select class="filter-kind">
    <option value="">All kinds</option>
    <option value="yaml">YAML</option>
    <option value="json">JSON</option>
    <option value="text">Text</option>
    <option value="binary">Binary</option>
    <option value="unknown">Unknown</option>
  </select>
  <span class="count"></span>
</form>
<table id="files-table">
<thead><tr><th>ID</th><th>Dump</th><th>Path</th><th>Kind</th><th>Size</th><th>SHA256</th><th>k8s</th><th>Actions</th></tr></thead>
<tbody>
{{range .Rows}}
<tr data-kind="{{.Kind}}" data-search="{{.Search}}">
  <td>{{.ID}}</td>
  <td>{{.DumpID}}</td>
  <td class="path"><a href="files/file-{{.ID}}.html">{{.Path}}</a></td>
  <td>{{badge .Kind}}</td>
  <td>{{humanBytes .Size}}</td>
  <td class="mono">{{shortHash .SHA256}}</td>
  <td class="mono">{{.K8s}}</td>
  <td><a href="files/file-{{.ID}}.html">view</a> · <a href="{{.RawHref}}">raw</a></td>
</tr>
{{end}}
</tbody>
</table>
`

const objectsBody = `
<h2>Kubernetes Objects</h2>
{{if not .Rows}}
<p>No parsed YAML metadata available.</p>
{{else}}
<form id="objects-form" class="toolbar" onsubmit="return false;">
  <input type="search" placeholder="Filter by kind, namespace, name…" autocomplete="off">
  <span class="count"></span>
</form>
<table id="objects-table">
<thead><tr><th>Kind</th><th>apiVersion</th><th>Namespace</th><th>Name</th><th>File</th><th>Raw</th></tr></thead>
<tbody>
{{range .Rows}}
<tr data-search="{{.Search}}">
  <td>{{.Kind}}</td>
  <td class="mono">{{.APIVersion}}</td>
  <td>{{.Namespace}}</td>
  <td>{{.Name}}</td>
  <td class="path"><a href="files/file-{{.FileID}}.html">{{.Path}}</a></td>
  <td><a href="{{.RawHref}}">raw</a></td>
</tr>
{{end}}
</tbody>
</table>
{{end}}
`

const dumpBody = `
<div class="breadcrumbs"><a href="../index.html">Overview</a> / Dump {{.Dump.ID}}</div>
<h2>Dump {{.Dump.ID}} — {{.Dump.RootName}}</h2>
<dl class="meta">
  <dt>Source</dt><dd class="mono">{{.Dump.SourcePath}}</dd>
  <dt>Source type</dt><dd>{{.Dump.SourceType}}</dd>
  <dt>Source SHA256</dt><dd class="mono">{{.Dump.SourceSHA256}}</dd>
  <dt>Imported</dt><dd>{{.Dump.ImportedAt}}</dd>
  <dt>Files</dt><dd>{{.FileCount}}</dd>
  <dt>Total bytes</dt><dd>{{humanBytes .Bytes}}</dd>
</dl>

<div class="cards">
  <div class="card sev-card critical"><div class="label">Critical</div><div class="value">{{.Critical}}</div></div>
  <div class="card sev-card warning"><div class="label">Warning</div><div class="value">{{.Warning}}</div></div>
  <div class="card sev-card info"><div class="label">Info</div><div class="value">{{.Info}}</div></div>
</div>

{{if .HasPXCTimeline}}
<p><a href="../pxc-timeline.html#tl-dump-{{.Dump.ID}}">View the PXC timeline for this dump →</a></p>
{{end}}
{{if .HasBackups}}
<p><a href="../backups.html#bk-dump-{{.Dump.ID}}">View backups for this dump →</a></p>
{{end}}

{{if .Findings}}
<h3>Concerns ({{len .Findings}})</h3>
{{template "findings" .Findings}}
{{end}}

<h3>By kind</h3>
<div class="cards">
{{range $k, $v := .KindCounts}}
  <div class="card"><div class="label">{{$k}}</div><div class="value">{{$v}}</div></div>
{{end}}
</div>
<h3>Files in this dump</h3>
<table>
<thead><tr><th>ID</th><th>Path</th><th>Kind</th><th>Size</th><th>SHA256</th><th>Actions</th></tr></thead>
<tbody>
{{range .Rows}}
<tr>
  <td>{{.ID}}</td>
  <td class="path"><a href="../files/file-{{.ID}}.html">{{.Path}}</a></td>
  <td>{{badge .Kind}}</td>
  <td>{{humanBytes .Size}}</td>
  <td class="mono">{{shortHash .SHA256}}</td>
  <td><a href="../files/file-{{.ID}}.html">view</a> · <a href="../{{.RawHref}}">raw</a></td>
</tr>
{{end}}
</tbody>
</table>
`

// findingsFragment is included as a named template into every page that
// renders findings (file, dump, concerns). It receives []findingRow as data.
const findingsFragment = `{{define "findings"}}
<div class="findings">
{{range $i, $f := .}}
<div class="finding" id="finding-{{$f.FileID}}-{{$i}}">
  <div class="finding-head">
    {{sevBadge $f.Severity}}
    <span class="finding-rule mono">{{$f.Rule}}</span>
    <span class="finding-target"><a href="{{$f.FileHref}}">{{$f.Kind}} {{$f.Namespace}}/{{$f.Name}}</a></span>
  </div>
  <div class="finding-title">{{$f.Title}}</div>
  {{if $f.Detail}}<div class="finding-detail mono">{{$f.Detail}}</div>{{end}}
  <details class="investigate">
    <summary>Investigate · ask AI or search</summary>
    <div class="investigate-actions">
      <a class="btn" href="{{$f.GoogleURL}}" target="_blank" rel="noopener">Google search</a>
    </div>
    <div class="code-wrap">
      <button class="copy" data-target="prompt-{{$f.FileID}}-{{$i}}">Copy prompt</button>
      <pre class="code"><code id="prompt-{{$f.FileID}}-{{$i}}">{{$f.Prompt}}</code></pre>
    </div>
  </details>
</div>
{{end}}
</div>
{{end}}`

const fileBody = `
<div class="breadcrumbs">
  <a href="../index.html">Overview</a> /
  <a href="../dumps/dump-{{.File.DumpID}}.html">Dump {{.File.DumpID}}</a> /
  {{.File.RelativePath}}
</div>
<h2>{{.File.FileName}} {{badge .File.FileKind}}</h2>
<dl class="meta">
  <dt>File ID</dt><dd>{{.File.ID}}</dd>
  <dt>Dump</dt><dd><a href="../dumps/dump-{{.File.DumpID}}.html">Dump {{.File.DumpID}}</a></dd>
  <dt>Relative path</dt><dd class="mono">{{.File.RelativePath}}</dd>
  <dt>Size</dt><dd>{{humanBytes .File.SizeBytes}} ({{.File.SizeBytes}} bytes)</dd>
  <dt>SHA256</dt><dd class="mono">{{.File.SHA256}}</dd>
  <dt>Kind</dt><dd>{{.File.FileKind}}</dd>
  {{if .File.ContentType}}<dt>Content-Type</dt><dd>{{.File.ContentType}}</dd>{{end}}
  {{if .File.Extension}}<dt>Extension</dt><dd>{{.File.Extension}}</dd>{{end}}
  {{if .LineCountValid}}<dt>Lines</dt><dd>{{.LineCount}}</dd>{{end}}
  {{if .File.ModifiedTime}}<dt>Modified</dt><dd>{{.File.ModifiedTime}}</dd>{{end}}
  {{if .File.FileMode}}<dt>Mode</dt><dd class="mono">{{.File.FileMode}}</dd>{{end}}
  <dt>Raw file</dt><dd><a href="../{{.RawHref}}">{{.RawHref}}</a></dd>
</dl>

{{if .Summary}}
<div class="summary-line"><strong>Summary:</strong> {{.Summary}}</div>
{{end}}

{{if .BackupContributions}}
<div class="bk-contrib">
  <strong>Backup timeline contributions:</strong>
  <ul>
  {{range .BackupContributions}}
    <li><a href="../backups.html#op-{{.OpKey}}">{{.Engine}}/{{.Name}}</a>
        <span class="bk-status bk-{{.Status}}">{{.Status}}</span>
        {{if .EventList}}<span class="muted">— {{.EventList}}</span>{{end}}
        {{if .When}}<span class="mono small">@ {{.When}}</span>{{end}}
    </li>
  {{end}}
  </ul>
</div>
{{end}}

{{if .Findings}}
<h3>Concerns ({{len .Findings}})</h3>
{{template "findings" .Findings}}
{{end}}

{{if .YAMLDocs}}
<h3>Kubernetes objects ({{len .YAMLDocs}})</h3>
<table>
<thead><tr><th>apiVersion</th><th>Kind</th><th>Namespace</th><th>Name</th><th>Parsed</th></tr></thead>
<tbody>
{{range .YAMLDocs}}
<tr>
  <td class="mono">{{.APIVersion}}</td>
  <td>{{.Kind}}</td>
  <td>{{.Namespace}}</td>
  <td>{{.Name}}</td>
  <td>{{if .ParsedOK}}ok{{else}}<span title="{{.ParseError}}">error</span>{{end}}</td>
</tr>
{{end}}
</tbody>
</table>
{{end}}

{{if .ShowText}}
<h3>Content</h3>
<div class="code-wrap">
  <button class="copy" data-target="file-content">Copy</button>
  <pre class="code numbered"><code id="file-content">{{numberedLines .TextContent}}</code></pre>
</div>
{{else}}
<div class="notice">
  This file is {{.File.FileKind}}. The raw bytes are available via the <a href="../{{.RawHref}}">raw file link</a>.
</div>
{{end}}
`

// concernsBody is the standalone /concerns.html page: every finding across every dump,
// with severity cards, a client-side filter, and the Investigate panel per row.
const concernsBody = `
<h2>Concerns</h2>
<div class="cards">
  <div class="card sev-card critical"><div class="label">Critical</div><div class="value">{{.Critical}}</div></div>
  <div class="card sev-card warning"><div class="label">Warning</div><div class="value">{{.Warning}}</div></div>
  <div class="card sev-card info"><div class="label">Info</div><div class="value">{{.Info}}</div></div>
</div>

{{if not .Findings}}
<p>No concerns detected.</p>
{{else}}
<form id="concerns-form" class="toolbar" onsubmit="return false;">
  <input type="search" placeholder="Filter by rule, namespace, kind, name…" autocomplete="off">
  <select class="filter-sev">
    <option value="">All severities</option>
    <option value="critical">Critical</option>
    <option value="warning">Warning</option>
    <option value="info">Info</option>
  </select>
  <span class="count"></span>
</form>
<div id="concerns-list">
{{template "findings" .Findings}}
</div>
{{end}}
`

func mustParse(name, body string) *template.Template {
	t, err := template.New(name).Funcs(funcs).Parse(baseHeader + body + baseFooter)
	if err != nil {
		panic(err)
	}
	if _, err := t.Parse(findingsFragment); err != nil {
		panic(err)
	}
	return t
}

const timelineBody = `
<h2>PXC Timeline</h2>
{{if not .Sections}}
<p>No Percona XtraDB Cluster log activity was detected in any imported dump.</p>
{{else}}
<p class="muted">Side-by-side chronological view of PXC, Galera, WSREP, SST/IST, MySQL, and PMM events
across detected nodes per dump. Events without a parseable timestamp inherit the previous timestamp.</p>

{{range .Sections}}
<section class="tl-dump" id="tl-dump-{{.DumpID}}-anchor">
  <h3 id="tl-dump-{{.DumpID}}">Dump {{.DumpID}}{{if .RootName}} — {{.RootName}}{{end}}</h3>
  <div class="cards">
    <div class="card"><div class="label">Detected nodes</div><div class="value">{{len .Nodes}}</div></div>
    <div class="card"><div class="label">Events</div><div class="value">{{.Total}}</div></div>
    <div class="card"><div class="label">Earliest</div><div class="value mono small">{{.Earliest}}</div></div>
    <div class="card"><div class="label">Latest</div><div class="value mono small">{{.Latest}}</div></div>
    <div class="card sev-card warning"><div class="label">Warnings</div><div class="value">{{.Warnings}}</div></div>
    <div class="card sev-card critical"><div class="label">Errors</div><div class="value">{{.Errors}}</div></div>
    <div class="card"><div class="label">SST events</div><div class="value">{{.SSTCount}}</div></div>
    <div class="card"><div class="label">IST events</div><div class="value">{{.ISTCount}}</div></div>
    <div class="card"><div class="label">Nodes MySQL ready</div><div class="value">{{.NodesMySQLReady}} / {{len .Nodes}}</div></div>
    <div class="card"><div class="label">Nodes WSREP synced</div><div class="value">{{.NodesWSREP}} / {{len .Nodes}}</div></div>
  </div>
  {{if .ParsePartial}}
  <div class="notice">Some log lines had no parseable timestamp; they were grouped with the previous timestamp.</div>
  {{end}}

  <h4>Node summary</h4>
  <div class="node-cards">
  {{range .NodeCards}}
    <div class="node-card">
      <div class="node-name">{{.Name}}</div>
      <dl>
        <dt>First seen</dt><dd class="mono small">{{.FirstSeen}}</dd>
        <dt>Last seen</dt><dd class="mono small">{{.LastSeen}}</dd>
        <dt>MySQL ready</dt><dd class="mono small">{{.MySQLReady}}</dd>
        <dt>WSREP ready</dt><dd class="mono small">{{.WSREPReady}}</dd>
        <dt>Synced</dt><dd class="mono small">{{.SyncedAt}}</dd>
        <dt>Donor</dt><dd>{{yesNo .ActedAsDonor}}</dd>
        <dt>Joiner</dt><dd>{{yesNo .ActedAsJoiner}}</dd>
        <dt>SST</dt><dd>{{yesNo .HasSST}}</dd>
        <dt>IST</dt><dd>{{yesNo .HasIST}}</dd>
        <dt>Warnings</dt><dd>{{.Warnings}}</dd>
        <dt>Errors</dt><dd>{{.Errors}}</dd>
        <dt>Total events</dt><dd>{{.Total}}</dd>
      </dl>
    </div>
  {{end}}
  </div>

  <h4>Timeline</h4>
  <form class="toolbar tl-filter" data-target-section="tl-dump-{{.DumpID}}" onsubmit="return false;">
    <input type="search" placeholder="Filter by node, event type, summary…" autocomplete="off">
    <select class="tl-sev">
      <option value="">All severities</option>
      <option value="info">Info</option>
      <option value="warning">Warning</option>
      <option value="error">Error</option>
      <option value="critical">Critical</option>
    </select>
    <label><input type="checkbox" class="tl-only-issues"> Warnings & errors only</label>
    <label><input type="checkbox" class="tl-only-transfer"> SST / IST only</label>
    <label><input type="checkbox" class="tl-only-ready"> Ready / sync only</label>
    <span class="count"></span>
  </form>
  <div class="tl-wrap" id="tl-dump-{{.DumpID}}">
    <table class="tl-table">
      <thead>
        <tr>
          <th>Time (UTC)</th>
          {{range .Nodes}}<th>{{.}}</th>{{end}}
        </tr>
      </thead>
      <tbody>
        {{range .Buckets}}
        <tr class="tl-row">
          <td class="mono small">{{.Timestamp}}</td>
          {{range .Cells}}
            <td class="tl-cell">
              {{range .}}
              <details class="tl-evt sev-{{.Severity}}" data-search="{{.SearchKey}}" data-sev="{{.Severity}}" data-type="{{.EventType}}">
                <summary>
                  {{evtBadge .EventType}}
                  {{if .Severity}}{{sevBadge .Severity}}{{end}}
                  <span class="tl-summary">{{.Summary}}</span>
                </summary>
                <div class="tl-evt-body">
                  <div class="tl-evt-meta">
                    <span class="mono small">{{.Timestamp}}</span>
                    {{if .Component}}<span class="mono small">{{.Component}}</span>{{end}}
                    <a href="{{.FileHref}}">file · line {{.LineNumber}}</a>
                    <a href="{{.RawHref}}">raw</a>
                  </div>
                  <pre class="code">{{.Raw}}</pre>
                </div>
              </details>
              {{end}}
            </td>
          {{end}}
        </tr>
        {{end}}
      </tbody>
    </table>
  </div>
</section>
{{end}}
{{end}}
`

const backupsBody = `
<h2>Backups</h2>
{{if not .Sections}}
<p>No Percona backup or restore objects were detected in any imported dump.</p>
{{else}}
<p class="muted">Per-engine view of Percona backup and restore activity, correlated from
backup CRDs, Kubernetes Jobs/Pods/Events, and backup pod logs.</p>

<div class="cards">
  <div class="card"><div class="label">Total operations</div><div class="value">{{.Summary.Total}}</div></div>
  <div class="card sev-card info"><div class="label">Succeeded</div><div class="value">{{.Summary.Succeeded}}</div></div>
  <div class="card sev-card critical"><div class="label">Failed</div><div class="value">{{.Summary.Failed}}</div></div>
  <div class="card sev-card warning"><div class="label">Running</div><div class="value">{{.Summary.Running}}</div></div>
  <div class="card"><div class="label">Pending</div><div class="value">{{.Summary.Pending}}</div></div>
  <div class="card"><div class="label">Unknown</div><div class="value">{{.Summary.Unknown}}</div></div>
  <div class="card"><div class="label">Backups</div><div class="value">{{.Summary.Backups}}</div></div>
  <div class="card"><div class="label">Restores</div><div class="value">{{.Summary.Restores}}</div></div>
  <div class="card sev-card warning"><div class="label">Log warnings</div><div class="value">{{.Summary.Warnings}}</div></div>
  <div class="card sev-card critical"><div class="label">Log errors</div><div class="value">{{.Summary.Errors}}</div></div>
</div>

{{range .Sections}}
<section class="bk-dump" id="{{.Anchor}}">
  <h3>Dump {{.DumpID}}{{if .RootName}} — {{.RootName}}{{end}}</h3>

  {{range .Engines}}
  <h4>{{.Title}}</h4>
  {{if .Ops}}
  <table class="bk-ops-table">
    <thead><tr>
      <th>Namespace</th><th>Cluster</th><th>Name</th>
      <th>Status</th><th>Storage</th>
      <th>Started</th><th>Completed</th><th>Duration</th>
      <th>Warnings</th><th>Errors</th><th>Source</th>
    </tr></thead>
    <tbody>
    {{range .Ops}}
    <tr class="bk-op" id="op-{{.OpKey}}" data-search="{{.SearchKey}}" data-engine="{{.Engine}}" data-status="{{.Status}}" data-ns="{{.Namespace}}" data-cluster="{{.Cluster}}">
      <td>{{.Namespace}}</td>
      <td>{{.Cluster}}</td>
      <td class="mono">{{.Name}}</td>
      <td><span class="bk-status bk-{{.Status}}">{{.Status}}</span></td>
      <td class="mono small">{{.Storage}}</td>
      <td class="mono small">{{.Started}}</td>
      <td class="mono small">{{.Completed}}</td>
      <td class="mono small">{{.Duration}}</td>
      <td>{{.Warnings}}</td>
      <td>{{.Errors}}</td>
      <td>
        {{range .SourceFiles}}<a href="{{.Href}}" title="{{.Path}}">file-{{.FileID}}</a> · <a href="{{.RawHref}}">raw</a><br>{{end}}
      </td>
    </tr>
    {{if .Destination}}
    <tr class="bk-op-dest"><td colspan="11" class="mono small">→ {{.Destination}}</td></tr>
    {{end}}
    {{end}}
    </tbody>
  </table>
  {{end}}
  {{if .Restores}}
  <p class="muted">Restores</p>
  <table class="bk-ops-table">
    <thead><tr>
      <th>Namespace</th><th>Cluster</th><th>Name</th>
      <th>Status</th><th>Started</th><th>Completed</th><th>Source</th>
    </tr></thead>
    <tbody>
    {{range .Restores}}
    <tr class="bk-op" id="op-{{.OpKey}}" data-search="{{.SearchKey}}" data-engine="{{.Engine}}" data-status="{{.Status}}">
      <td>{{.Namespace}}</td><td>{{.Cluster}}</td>
      <td class="mono">{{.Name}}</td>
      <td><span class="bk-status bk-{{.Status}}">{{.Status}}</span></td>
      <td class="mono small">{{.Started}}</td>
      <td class="mono small">{{.Completed}}</td>
      <td>{{range .SourceFiles}}<a href="{{.Href}}">file-{{.FileID}}</a><br>{{end}}</td>
    </tr>
    {{end}}
    </tbody>
  </table>
  {{end}}
  {{end}}

  <h4>Timeline events</h4>
  <form class="toolbar bk-filter" data-target-section="{{.Anchor}}" onsubmit="return false;">
    <input type="search" placeholder="Filter by namespace, name, type, summary…" autocomplete="off">
    <select class="bk-engine">
      <option value="">All engines</option>
      <option value="pxc">PXC</option>
      <option value="postgres">PostgreSQL</option>
      <option value="mongodb">MongoDB</option>
      <option value="everest">Everest</option>
    </select>
    <select class="bk-status">
      <option value="">All statuses</option>
      <option value="Succeeded">Succeeded</option>
      <option value="Failed">Failed</option>
      <option value="Running">Running</option>
      <option value="Pending">Pending</option>
      <option value="Unknown">Unknown</option>
    </select>
    <label><input type="checkbox" class="bk-only-failed"> Failed only</label>
    <label><input type="checkbox" class="bk-only-running"> Running only</label>
    <label><input type="checkbox" class="bk-only-issues"> Warnings & errors only</label>
    <span class="count"></span>
  </form>
  <table class="bk-events">
    <thead><tr>
      <th>Time (UTC)</th><th>Engine</th><th>Namespace</th><th>Cluster</th>
      <th>Backup</th><th>Event</th><th>Severity</th><th>Summary</th><th>Source</th>
    </tr></thead>
    <tbody>
    {{range .Events}}
    <tr class="bk-evt" data-search="{{.SearchKey}}" data-engine="{{.Engine}}" data-sev="{{.Severity}}" data-type="{{.Type}}">
      <td class="mono small">{{.Timestamp}}</td>
      <td>{{.Engine}}</td>
      <td>{{.Namespace}}</td>
      <td>{{.Cluster}}</td>
      <td class="mono"><a href="#op-{{.OpKey}}">{{.OpName}}</a></td>
      <td>{{evtBadge .Type}}</td>
      <td>{{if .Severity}}{{sevBadge .Severity}}{{end}}</td>
      <td>{{.Summary}}</td>
      <td>
        {{if .LineNumber}}<a href="{{.FileHref}}">line {{.LineNumber}}</a> · {{end}}
        <a href="{{.RawHref}}">raw</a>
      </td>
    </tr>
    {{end}}
    </tbody>
  </table>
</section>
{{end}}
{{end}}
`

var (
	tmplIndex    = mustParse("index", indexBody)
	tmplFiles    = mustParse("files", filesBody)
	tmplObjects  = mustParse("objects", objectsBody)
	tmplDump     = mustParse("dump", dumpBody)
	tmplFile     = mustParse("file", fileBody)
	tmplConcerns = mustParse("concerns", concernsBody)
	tmplTimeline = mustParse("timeline", timelineBody)
	tmplBackups  = mustParse("backups", backupsBody)
)
