package report

import (
	"fmt"
	"html/template"
	"strings"
)

var funcs = template.FuncMap{
	"shortHash": func(s string) string {
		if len(s) > 12 {
			return s[:12]
		}
		return s
	},
	"humanBytes": humanBytes,
	"depth": func(p string) string {
		return strings.Repeat("../", strings.Count(p, "/"))
	},
	"badge": func(kind string) template.HTML {
		k := template.HTMLEscapeString(kind)
		return template.HTML(`<span class="badge ` + k + `">` + k + `</span>`)
	},
	"sevBadge": func(sev string) template.HTML {
		s := template.HTMLEscapeString(sev)
		return template.HTML(`<span class="sev sev-` + s + `">` + s + `</span>`)
	},
}

func humanBytes(n int64) string {
	const unit = 1024
	if n < unit {
		return fmt.Sprintf("%d B", n)
	}
	div, exp := int64(unit), 0
	for x := n / unit; x >= unit; x /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f %cB", float64(n)/float64(div), "KMGTPE"[exp])
}

const baseHeader = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{{.Title}} — db-k8s</title>
<link rel="stylesheet" href="{{.AssetBase}}assets/style.css">
</head>
<body>
<header class="site">
  <h1>db-k8s</h1>
  <nav>
    <a href="{{.AssetBase}}index.html"{{if eq .Nav "index"}} class="active"{{end}}>Overview</a>
    <a href="{{.AssetBase}}concerns.html"{{if eq .Nav "concerns"}} class="active"{{end}}>Concerns</a>
    <a href="{{.AssetBase}}files.html"{{if eq .Nav "files"}} class="active"{{end}}>Files</a>
    <a href="{{.AssetBase}}objects.html"{{if eq .Nav "objects"}} class="active"{{end}}>Kubernetes Objects</a>
  </nav>
</header>
<main>
`

const baseFooter = `
</main>
<footer class="site">
  Generated by db-k8s · {{.GeneratedAt}}
</footer>
<script src="{{.AssetBase}}assets/script.js"></script>
</body>
</html>`

const indexBody = `
<h2>Overview</h2>
<div class="cards">
  <div class="card"><div class="label">Dumps</div><div class="value">{{.TotalDumps}}</div></div>
  <div class="card"><div class="label">Files</div><div class="value">{{.TotalFiles}}</div></div>
  <div class="card"><div class="label">Total bytes</div><div class="value">{{humanBytes .TotalBytes}}</div></div>
  <div class="card sev-card critical"><div class="label">Critical</div><div class="value">{{.Critical}}</div></div>
  <div class="card sev-card warning"><div class="label">Warning</div><div class="value">{{.Warning}}</div></div>
  <div class="card sev-card info"><div class="label">Info</div><div class="value">{{.Info}}</div></div>
</div>

<div class="cards">
  <div class="card"><div class="label">YAML</div><div class="value">{{index .KindCounts "yaml"}}</div></div>
  <div class="card"><div class="label">JSON</div><div class="value">{{index .KindCounts "json"}}</div></div>
  <div class="card"><div class="label">Text</div><div class="value">{{index .KindCounts "text"}}</div></div>
  <div class="card"><div class="label">Binary</div><div class="value">{{index .KindCounts "binary"}}</div></div>
  <div class="card"><div class="label">Unknown</div><div class="value">{{index .KindCounts "unknown"}}</div></div>
</div>

{{if .TopCritical}}
<h3>Top critical concerns</h3>
<table>
<thead><tr><th>Severity</th><th>Rule</th><th>Object</th><th>Title</th></tr></thead>
<tbody>
{{range .TopCritical}}
<tr>
  <td>{{sevBadge .Severity}}</td>
  <td class="mono">{{.Rule}}</td>
  <td><a href="{{.FileHref}}">{{.Kind}} {{.Namespace}}/{{.Name}}</a></td>
  <td>{{.Title}}</td>
</tr>
{{end}}
</tbody>
</table>
<p><a href="concerns.html">See all concerns →</a></p>
{{end}}

<h3>Database</h3>
<p class="mono">{{.DBPath}}</p>

<h3>Dumps</h3>
<table>
<thead><tr><th>ID</th><th>Root</th><th>Source</th><th>Type</th><th>Files</th><th>Size</th><th>Imported</th></tr></thead>
<tbody>
{{range .Dumps}}
<tr>
  <td><a href="dumps/dump-{{.ID}}.html">{{.ID}}</a></td>
  <td>{{.RootName}}</td>
  <td class="mono">{{.SourcePath}}</td>
  <td>{{.SourceType}}</td>
  <td>{{.FileCount}}</td>
  <td>{{humanBytes .Bytes}}</td>
  <td>{{.ImportedAt}}</td>
</tr>
{{end}}
</tbody>
</table>
`

const filesBody = `
<h2>Files</h2>
<form id="files-form" class="toolbar" onsubmit="return false;">
  <input type="search" placeholder="Filter by path, name, hash, namespace…" autocomplete="off">
  <select class="filter-kind">
    <option value="">All kinds</option>
    <option value="yaml">YAML</option>
    <option value="json">JSON</option>
    <option value="text">Text</option>
    <option value="binary">Binary</option>
    <option value="unknown">Unknown</option>
  </select>
  <span class="count"></span>
</form>
<table id="files-table">
<thead><tr><th>ID</th><th>Dump</th><th>Path</th><th>Kind</th><th>Size</th><th>SHA256</th><th>k8s</th><th>Actions</th></tr></thead>
<tbody>
{{range .Rows}}
<tr data-kind="{{.Kind}}" data-search="{{.Search}}">
  <td>{{.ID}}</td>
  <td>{{.DumpID}}</td>
  <td class="path"><a href="files/file-{{.ID}}.html">{{.Path}}</a></td>
  <td>{{badge .Kind}}</td>
  <td>{{humanBytes .Size}}</td>
  <td class="mono">{{shortHash .SHA256}}</td>
  <td class="mono">{{.K8s}}</td>
  <td><a href="files/file-{{.ID}}.html">view</a> · <a href="{{.RawHref}}">raw</a></td>
</tr>
{{end}}
</tbody>
</table>
`

const objectsBody = `
<h2>Kubernetes Objects</h2>
{{if not .Rows}}
<p>No parsed YAML metadata available.</p>
{{else}}
<form id="objects-form" class="toolbar" onsubmit="return false;">
  <input type="search" placeholder="Filter by kind, namespace, name…" autocomplete="off">
  <span class="count"></span>
</form>
<table id="objects-table">
<thead><tr><th>Kind</th><th>apiVersion</th><th>Namespace</th><th>Name</th><th>File</th><th>Raw</th></tr></thead>
<tbody>
{{range .Rows}}
<tr data-search="{{.Search}}">
  <td>{{.Kind}}</td>
  <td class="mono">{{.APIVersion}}</td>
  <td>{{.Namespace}}</td>
  <td>{{.Name}}</td>
  <td class="path"><a href="files/file-{{.FileID}}.html">{{.Path}}</a></td>
  <td><a href="{{.RawHref}}">raw</a></td>
</tr>
{{end}}
</tbody>
</table>
{{end}}
`

const dumpBody = `
<div class="breadcrumbs"><a href="../index.html">Overview</a> / Dump {{.Dump.ID}}</div>
<h2>Dump {{.Dump.ID}} — {{.Dump.RootName}}</h2>
<dl class="meta">
  <dt>Source</dt><dd class="mono">{{.Dump.SourcePath}}</dd>
  <dt>Source type</dt><dd>{{.Dump.SourceType}}</dd>
  <dt>Source SHA256</dt><dd class="mono">{{.Dump.SourceSHA256}}</dd>
  <dt>Imported</dt><dd>{{.Dump.ImportedAt}}</dd>
  <dt>Files</dt><dd>{{.FileCount}}</dd>
  <dt>Total bytes</dt><dd>{{humanBytes .Bytes}}</dd>
</dl>

<div class="cards">
  <div class="card sev-card critical"><div class="label">Critical</div><div class="value">{{.Critical}}</div></div>
  <div class="card sev-card warning"><div class="label">Warning</div><div class="value">{{.Warning}}</div></div>
  <div class="card sev-card info"><div class="label">Info</div><div class="value">{{.Info}}</div></div>
</div>

{{if .Findings}}
<h3>Concerns ({{len .Findings}})</h3>
{{template "findings" .Findings}}
{{end}}

<h3>By kind</h3>
<div class="cards">
{{range $k, $v := .KindCounts}}
  <div class="card"><div class="label">{{$k}}</div><div class="value">{{$v}}</div></div>
{{end}}
</div>
<h3>Files in this dump</h3>
<table>
<thead><tr><th>ID</th><th>Path</th><th>Kind</th><th>Size</th><th>SHA256</th><th>Actions</th></tr></thead>
<tbody>
{{range .Rows}}
<tr>
  <td>{{.ID}}</td>
  <td class="path"><a href="../files/file-{{.ID}}.html">{{.Path}}</a></td>
  <td>{{badge .Kind}}</td>
  <td>{{humanBytes .Size}}</td>
  <td class="mono">{{shortHash .SHA256}}</td>
  <td><a href="../files/file-{{.ID}}.html">view</a> · <a href="../{{.RawHref}}">raw</a></td>
</tr>
{{end}}
</tbody>
</table>
`

// findingsFragment is included as a named template into every page that
// renders findings (file, dump, concerns). It receives []findingRow as data.
const findingsFragment = `{{define "findings"}}
<div class="findings">
{{range $i, $f := .}}
<div class="finding" id="finding-{{$f.FileID}}-{{$i}}">
  <div class="finding-head">
    {{sevBadge $f.Severity}}
    <span class="finding-rule mono">{{$f.Rule}}</span>
    <span class="finding-target"><a href="{{$f.FileHref}}">{{$f.Kind}} {{$f.Namespace}}/{{$f.Name}}</a></span>
  </div>
  <div class="finding-title">{{$f.Title}}</div>
  {{if $f.Detail}}<div class="finding-detail mono">{{$f.Detail}}</div>{{end}}
  <details class="investigate">
    <summary>Investigate · ask AI or search</summary>
    <div class="investigate-actions">
      <a class="btn" href="{{$f.GoogleURL}}" target="_blank" rel="noopener">Google search</a>
    </div>
    <div class="code-wrap">
      <button class="copy" data-target="prompt-{{$f.FileID}}-{{$i}}">Copy prompt</button>
      <pre class="code"><code id="prompt-{{$f.FileID}}-{{$i}}">{{$f.Prompt}}</code></pre>
    </div>
  </details>
</div>
{{end}}
</div>
{{end}}`

const fileBody = `
<div class="breadcrumbs">
  <a href="../index.html">Overview</a> /
  <a href="../dumps/dump-{{.File.DumpID}}.html">Dump {{.File.DumpID}}</a> /
  {{.File.RelativePath}}
</div>
<h2>{{.File.FileName}} {{badge .File.FileKind}}</h2>
<dl class="meta">
  <dt>File ID</dt><dd>{{.File.ID}}</dd>
  <dt>Dump</dt><dd><a href="../dumps/dump-{{.File.DumpID}}.html">Dump {{.File.DumpID}}</a></dd>
  <dt>Relative path</dt><dd class="mono">{{.File.RelativePath}}</dd>
  <dt>Size</dt><dd>{{humanBytes .File.SizeBytes}} ({{.File.SizeBytes}} bytes)</dd>
  <dt>SHA256</dt><dd class="mono">{{.File.SHA256}}</dd>
  <dt>Kind</dt><dd>{{.File.FileKind}}</dd>
  {{if .File.ContentType}}<dt>Content-Type</dt><dd>{{.File.ContentType}}</dd>{{end}}
  {{if .File.Extension}}<dt>Extension</dt><dd>{{.File.Extension}}</dd>{{end}}
  {{if .LineCountValid}}<dt>Lines</dt><dd>{{.LineCount}}</dd>{{end}}
  {{if .File.ModifiedTime}}<dt>Modified</dt><dd>{{.File.ModifiedTime}}</dd>{{end}}
  {{if .File.FileMode}}<dt>Mode</dt><dd class="mono">{{.File.FileMode}}</dd>{{end}}
  <dt>Raw file</dt><dd><a href="../{{.RawHref}}">{{.RawHref}}</a></dd>
</dl>

{{if .Summary}}
<div class="summary-line"><strong>Summary:</strong> {{.Summary}}</div>
{{end}}

{{if .Findings}}
<h3>Concerns ({{len .Findings}})</h3>
{{template "findings" .Findings}}
{{end}}

{{if .YAMLDocs}}
<h3>Kubernetes objects ({{len .YAMLDocs}})</h3>
<table>
<thead><tr><th>apiVersion</th><th>Kind</th><th>Namespace</th><th>Name</th><th>Parsed</th></tr></thead>
<tbody>
{{range .YAMLDocs}}
<tr>
  <td class="mono">{{.APIVersion}}</td>
  <td>{{.Kind}}</td>
  <td>{{.Namespace}}</td>
  <td>{{.Name}}</td>
  <td>{{if .ParsedOK}}ok{{else}}<span title="{{.ParseError}}">error</span>{{end}}</td>
</tr>
{{end}}
</tbody>
</table>
{{end}}

{{if .ShowText}}
<h3>Content</h3>
<div class="code-wrap">
  <button class="copy" data-target="file-content">Copy</button>
  <pre class="code"><code id="file-content">{{.TextContent}}</code></pre>
</div>
{{else}}
<div class="notice">
  This file is {{.File.FileKind}}. The raw bytes are available via the <a href="../{{.RawHref}}">raw file link</a>.
</div>
{{end}}
`

// concernsBody is the standalone /concerns.html page: every finding across every dump,
// with severity cards, a client-side filter, and the Investigate panel per row.
const concernsBody = `
<h2>Concerns</h2>
<div class="cards">
  <div class="card sev-card critical"><div class="label">Critical</div><div class="value">{{.Critical}}</div></div>
  <div class="card sev-card warning"><div class="label">Warning</div><div class="value">{{.Warning}}</div></div>
  <div class="card sev-card info"><div class="label">Info</div><div class="value">{{.Info}}</div></div>
</div>

{{if not .Findings}}
<p>No concerns detected.</p>
{{else}}
<form id="concerns-form" class="toolbar" onsubmit="return false;">
  <input type="search" placeholder="Filter by rule, namespace, kind, name…" autocomplete="off">
  <select class="filter-sev">
    <option value="">All severities</option>
    <option value="critical">Critical</option>
    <option value="warning">Warning</option>
    <option value="info">Info</option>
  </select>
  <span class="count"></span>
</form>
<div id="concerns-list">
{{template "findings" .Findings}}
</div>
{{end}}
`

func mustParse(name, body string) *template.Template {
	t, err := template.New(name).Funcs(funcs).Parse(baseHeader + body + baseFooter)
	if err != nil {
		panic(err)
	}
	if _, err := t.Parse(findingsFragment); err != nil {
		panic(err)
	}
	return t
}

var (
	tmplIndex    = mustParse("index", indexBody)
	tmplFiles    = mustParse("files", filesBody)
	tmplObjects  = mustParse("objects", objectsBody)
	tmplDump     = mustParse("dump", dumpBody)
	tmplFile     = mustParse("file", fileBody)
	tmplConcerns = mustParse("concerns", concernsBody)
)
